### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mhoran** [iamacarpet/go-winpty#2]
Hey @iamacarpet! We're interested in using this code in Cloud Foundry on Windows to provide SSH support on Windows Server 2016. Given there's no license associated with this project, we can't currently do so. Do you intend to release this under an open source license? If published under MIT/BSD/Apache 2.0, this would save us a bunch of effort.

Thanks!

**Comment by iamacarpet** [comment]
Hello @mhoran,

Sure thing, added an Apache 2.0 license.

If you make any improvements, I'd appreciate a PR to merge them into our own projects.

Regards,
iamacarpet

**Comment by mhoran** [comment]
Awesome, thanks! Do expect pull requests (once we get started!)
